### ISSUE TITLE
Scaling of frequency and decay rate

### ISSUE THREAD

**Issue by adamiao** [aaren/pharminv#1]
There seems to be some issues with the output calculation of frequency and decay rate. The "number" coming out of the code are correct, but with a 10^3 order of magnitude mistake. The fact that both the (real) frequency and decay rate comes wrong with the same order of magnitude makes sense, since:

complex frequency = real frequency + i \* decay rate

I have a test code that I'm sending over through your email if you want to see!

Best regards,

Alex

**Comment by aaren** [comment]
I think you need to set the `dt` argument in `invert`. You've used 

``` python
time = np.linspace(0, 10, 10000)

signal = 2.1 * np.cos(2 * np.pi * time * 10) * np.exp(-0.0343 * time)

inversion = harminv.invert(signal, fmin=5, fmax=15)
```

Your time implies `dt = 10 / 10000 = 0.001`, so you need to call `invert` like

``` python
inversion = harminv.invert(signal, fmin=5, fmax=15, dt=0.001)
```

The default `dt` is 1, giving a 10^3 difference in any time based outputs.

**Comment by adamiao** [comment]
Hey Aaron!

You are absolutely right. It did not even cross my mind, although I knew it
was something small.

Thanks again for this python interface.

Best,

Alex

2015-04-06 6:49 GMT-04:00 aaren notifications@github.com:

**Comment by aaren** [comment]
No problem, I'm glad it is working for you :)
