### ISSUE TITLE
Wrong Answers

### ISSUE THREAD

**Issue by tomfallen** [aaren/pharminv#3]
Edit:  the errors below have to do with the settings in the example code.  Changing fmin or setting dt helps.  Not I'm getting the real sinusoid divided up into two entries, one with the same frequence but negative, both at half the amplitude.  Is there some setting I'm missing?

---

Using Ubuntu 14.04, I installed harminv from apt-get, and pharminv using pip.

The example provided here runs without error, but does not appear to return the correct answer.  The output of >> inversion is:

rec.array([ (-8.6253957423602e-11, 2.0112201361652824, 4.0738465133229765e-10, -0.009925186956024614, -2.7301732469689393e-08, 0.5000000012106294)], 
      dtype=[('frequency', '<f8'), ('amplitude', '<f8'), ('phase', '<f8'), ('decay', '<f8'), ('Q', '<f8'), ('error', '<f8')])

I tried removing one of the sinusoids and the result is similar.

By the way, thanks for writing what looks like a very useful tool.

**Comment by aaren** [comment]
Thanks for reporting this. Are you following the example in the readme? i.e.

``` python
import numpy as np
import harminv

time = np.linspace(0, 1, 1000)

signal = np.cos(2 * np.pi * time * 10) + np.cos(2 * np.pi * time * 20)

inversion = harminv.invert(signal, fmin=1, fmax=100)
```

Do you know what your machine gives you when you use `harminv` on the command line? You would have to write a file with the sinusoids in it to test.

I've noticed that harminv can be very sensitive to fmin / fmax / nf.

**Comment by aaren** [comment]
I've spotted the problem: `harminv.invert` needs to be given `dt`, which in this case is `0.001` rather than the default of `1`.

The following should work:

``` python
inversion = harminv.invert(signal, fmin=1, fmax=100, dt=0.001)
```

**Comment by tomfallen** [comment]
Thanks for the quick response.  Adding dt=0.001 is what I needed.

Also, unrelated, I couldn't build from source without cython, as I get an error that charminv.c is missing when calling "python setup.py build".  I'm not sure if this is my fault of a missing file.  With cython installed it builds just fine.

Again, thanks for sharing this.  Access to harminv from Python is super helpful.

**Comment by aaren** [comment]
Yes you will need cython to build it, that's how the link to the c library is managed.

I'm not really using this much anymore for my work - if you have any ideas for improvements then feel free to make suggestions.

**Comment by tomfallen** [comment]
If we end up using for our robotics stuff I'll try to incorporate improvements. For now my only suggestions is to print a warning in the except block after trying to import Cython saying that Cython is required.  Thanks again for making this code available.
